config/routes.rb
Rails.application.routes.draw do
  root 'riffs#index'
  
  resources :riffs do
    resources :comments
  end
  devise_for :users, controllers: { registrations: 'registrations' }

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :riff
  validates :content, presence: true
end

app/models/riff.rb
class Riff < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :user_id, presence: true
  validates :audio, presence: true
  has_attached_file :audio
  validates_attachment_content_type :audio, content_type: /\Aaudio\/.*\Z/
  scope :most_recent, -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :riffs, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :username, presence: true, length: { minimum: 3, maximum: 20 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_riff

  def create
    @comment = @riff.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      respond_to do |format|
        format.html { redirect_to :back, notice: "Your comment has been saved." }
        format.js
      end
    else
      flash[:alert] = "Something went wrong, please try again."
      redirect_to root_url
    end
  end

  def destroy
    @comment = @riff.comments.find(params[:id])

    if @comment.user == current_user
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to root_url, notice: "Comment deleted." }
        format.js
      end
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end

    def set_riff
      @riff = Riff.find(params[:riff_id])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  private

    def sign_up_params
      params.require(:user).permit(:email, :username, :password, :password_confirmation)
    end

    def account_update_params
      params.require(:user).permit(:email, :username, :password, :password_confirmation, :current_password)
    end
end

app/controllers/riffs_controller.rb
class RiffsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_riff, only: [:show, :edit, :update, :destroy]
  before_action :owned_riff, only: [:edit, :update, :destroy]

  def index
    @riffs = Riff.most_recent
  end

  def show
  end

  def new
    @riff = current_user.riffs.build
  end

  def create
    @riff = current_user.riffs.build(riff_params)
    if @riff.save
      redirect_to riffs_url
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @riff.update(riff_params)
      redirect_to @riff
    else
      render :edit
    end
  end

  def destroy
    @riff.destroy
    redirect_to riffs_url
  end

  private

    def riff_params
      params.require(:riff).permit(:audio, :description)
    end

    def set_riff
      @riff = Riff.find(params[:id])
    end

    def owned_riff
      unless current_user == @riff.user
        flash[:alert] = "That riff doesn't belong to you!"
        redirect_to root_path
      end
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_for(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end

  def current_location?(*args)
    options = args.extract_options!
    options.each do |key, val|
      return false unless eval("controller.#{key.to_s}_name") == val
    end
    true
  end

  def background_image
    return "registration-bg" if current_location?(controller: "registrations", action: "new") || current_location?(controller: "registrations", action: "create")
    return "login-bg" if current_location?(controller: "sessions", action: "new")
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/riffs_helper.rb
module RiffsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/comments/_comment.html.haml
.comment
  .username
    = comment.user.username
  .comment-content
    = comment.content
  - if comment.user == current_user
    = link_to riff_comment_path(riff, comment), method: :delete, data: { confirm: "Are you sure?" }, remote: true do
      %span.glyphicon.glyphicon-remove.delete-comment

app/views/comments/create.js.erb
$('#comments_<%= @riff.id %>').append("<%=j render @comment, riff: @riff %>");
$('#comment_content_<%= @riff.id %>').val('');

app/views/comments/destroy.js.erb
$('#comments_<%= @riff.id %>').html("<%=j render @riff.comments, riff: @riff %>");

app/views/layouts/_flashes.html.haml
- flash.each do |message_type, message|
  %div{:class => "alert #{alert_for(message_type)} alert-dismissible"}
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
      %span{"aria-hidden" => "true"} &times;
    = message

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container.navbar-container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Riffer", root_path, class: "navbar-brand"
    .collapse.navbar-collapse#bs-navbar-collapse-1
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li= link_to "New Riff", new_riff_path
          %li= link_to "Logout", destroy_user_session_path, method: :delete
        - else
          %li= link_to "Login", new_user_session_path
          %li= link_to "Register", new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    
    %title Riffer
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    
    / HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  %body{class: background_image}
    = render "layouts/header"
    .container
      = render "layouts/flashes"
      = yield

app/views/riffs/_form.html.haml
.form-wrapper
  = simple_form_for @riff, html: { multipart: true } do |f|
    .row
      .col-md-12
        = f.error_notification
    .form-group
      %h4 Upload an mp3 (required):
      = f.input :audio, label: false
    .form-group
      = f.input :description, label: false, placeholder: 'Add a description...'
    = f.button :submit, class: 'btn-success btn-block'

app/views/riffs/_riff.html.haml
.riff
  .riff-head
    .username
      = riff.user.username
    .time-ago
      = time_ago_in_words riff.created_at
  .audio
    = render "shared/jplayer", filename: riff.audio.url, index: index
  .riff-bottom
    .description
      .description-content
        .username
          = riff.user.username
        = riff.description
        = link_to "edit", edit_riff_path(riff), class: "edit-link" if riff.user == current_user
    .comments{id: "comments_#{riff.id}"}
      - if riff.comments
        = render riff.comments, riff: riff
  .comment-like-form.row
    .comment-form
      = form_for([riff, riff.comments.build], remote: true) do |f|
        = f.text_field :content, placeholder: "Add a comment...", class: "comment_content", id: "comment_content_#{riff.id}"

app/views/riffs/edit.html.haml
.current-audio
  %h4 Current mp3:
  = render "shared/jplayer", filename: @riff.audio.url, index: 0

= render 'form'

.text-center
  = link_to "Delete Riff", @riff, method: :delete, data: { confirm: "Are you sure?" }
  |
  = link_to "Cancel", @riff

app/views/riffs/index.html.haml
.riffs-wrapper.row
  - @riffs.each_with_index do |riff, index|
    = render riff, index: index

app/views/riffs/new.html.haml
= render 'form'

app/views/riffs/show.html.haml
.riffs-wrapper.row
  = render @riff, index: 0

%p.text-center
  - if @riff.user == current_user
    = link_to "Edit Riff", edit_riff_path(@riff)
    |
  = link_to "Back", riffs_path

app/views/shared/_jplayer.html.erb
<div id="jquery_jplayer_<%= index %>" class="jp-jplayer"></div>
<div id="jp_container_<%= index %>" class="jp-audio" role="application" aria-label="media player">
  <div class="jp-type-single">
    <div class="jp-gui jp-interface">
      <div class="jp-controls">
        <button class="jp-play" role="button" tabindex="0">play</button>
        <button class="jp-stop" role="button" tabindex="0">stop</button>
      </div>
      <div class="jp-progress">
        <div class="jp-seek-bar">
          <div class="jp-play-bar"></div>
        </div>
      </div>
      <div class="jp-volume-controls">
        <button class="jp-mute" role="button" tabindex="0">mute</button>
        <button class="jp-volume-max" role="button" tabindex="0">max volume</button>
        <div class="jp-volume-bar">
          <div class="jp-volume-bar-value"></div>
        </div>
      </div>
      <div class="jp-time-holder">
        <div class="jp-current-time" role="timer" aria-label="time">&nbsp;</div>
        <div class="jp-duration" role="timer" aria-label="duration">&nbsp;</div>
        <div class="jp-toggles">
          <button class="jp-repeat" role="button" tabindex="0">repeat</button>
        </div>
      </div>
    </div>
    <!-- <div class="jp-details">
      <div class="jp-title" aria-label="title">&nbsp;</div>
    </div> -->
    <div class="jp-no-solution">
      <span>Update Required</span>
      To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $("#jquery_jplayer_<%= index %>").jPlayer({
      ready: function () {
        $(this).jPlayer("setMedia", {
          mp3: "<%= filename %>"
        });
      },
      play: function() { // To avoid multiple jPlayers playing together.
        $(this).jPlayer("pauseOthers");
      },
      cssSelectorAncestor: "#jp_container_<%= index %>",
      swfPath: "/js",
      supplied: "mp3",
      useStateClassSkin: true,
      autoBlur: false,
      smoothPlayBar: true,
      keyEnabled: true,
      remainingDuration: true,
      toggleDuration: true
    });
  });
</script>

app/views/static_pages/home.html.haml
%h2 Hello World

%p The time is now: #{Time.now}